.github/workflows/python-publish.yaml
Added GH workflow for automatic PyPI publishing on release
=> Added automatic PyPI publishing

examples/utils/parser.py, examples/visualization/mapping.py, examples/visualization/messages.py, examples/visualization/segmentation.py
This PR adds FastSAM to the general example. Prompts point and bounding-box are not supported - they require clicking on frame.
=> Adds FastSAM to examples.

depthai_nodes/ml/parsers/utils/medipipe.py
This PR implements better error printing when using wrong scale in MPPalmDetection parser.
=> Better error in MPPalmDetectionParser.

depthai_nodes/ml/parsers/fastsam.py, depthai_nodes/ml/parsers/yolo.py
This PR fixes the issues with RVC4 inference of YOLOv8 kpts, seg and FastSAM models.
=> Fix RVC4 inference of YOLO & FastSAM parsers

depthai_nodes/ml/parsers/scrfd.py
This PR refactors SCRFD parser. Works on both models: face detection and person detection.
=> Parsers-V2: Refactor SCRFD parser.

examples/utils/parser.py
This PR fixes merge commits for PR #98  because dev branch is protected i can not push commits there.
=> Release: Fix merge commits.

depthai_nodes/ml/parsers/hrnet.py, depthai_nodes/ml/parsers/image_output.py, depthai_nodes/ml/parsers/keypoints.py, depthai_nodes/ml/parsers/map_output.py
This PR refactors `HRNetParser`, `MapOutputParser`, and `ImageOutputParser` to v2.
=> Parsers-V2: Refactor HRNetParser, MapOutputParser, and ImageOutputParser

depthai_nodes/ml/parsers/classification.py, depthai_nodes/ml/parsers/classification_sequence.py, depthai_nodes/ml/parsers/detection.py, depthai_nodes/ml/parsers/hrnet.py, depthai_nodes/ml/parsers/image_output.py, depthai_nodes/ml/parsers/keypoints.py, depthai_nodes/ml/parsers/lane_detection.py, depthai_nodes/ml/parsers/map_output.py, depthai_nodes/ml/parsers/mediapipe_palm_detection.py, depthai_nodes/ml/parsers/mlsd.py, depthai_nodes/ml/parsers/ppdet.py, depthai_nodes/ml/parsers/regression.py, depthai_nodes/ml/parsers/scrfd.py, depthai_nodes/ml/parsers/segmentation.py, depthai_nodes/ml/parsers/superanimal_landmarker.py, depthai_nodes/ml/parsers/xfeat.py, depthai_nodes/ml/parsers/yunet.py
This PR adds type hints to all arguments in parser functions and type checks in all setter methods.
=> Type hints & type checking.

depthai_nodes/ml/messages/creators/detection.py, depthai_nodes/ml/parsers/yolo.py, depthai_nodes/ml/parsers/yunet.py, depthai_nodes/parsing_neural_network.py
This PR is opened to fix some small issues with the overload decorator methods, function imports and object type passing.
=> Fix: Adding miniature fixes

depthai_nodes/ml/parsers/segmentation.py
This PR modifies Segmentation Parser. We no longer need to set `background_class` because this is automatically detected out of tensor shapes. I found one bug in previous version. We have a multi-class segmentation model in the ZOO that outputs all classes in one tensor [1, H, W] and not in [n_classes, H, W]. Probably some postprocessing was added to the model (it is Deeplab). This is handled by setting a flag `classes_in_one_layer` and defaults to False. I believe this is rare case, so this paramter is optional and not neccesery to be added to the archive schema.
=> Handle special case in Segmentation parser.

depthai_nodes/ml/parsers/__init__.py, depthai_nodes/ml/parsers/embeddings.py
Add a simple parser for embeddings models. Its just passes the output of the NN as an dai.NNData output message
=> Parser for Embeddings NN models

.github/workflows/e2e_tests.yaml
This PR fixes simple bug in the e2e CI. First we need to checkout main branch and pull the changes and then checkout the desired branch.
=> Checkout main first and then pull the changes.

.github/workflows/ci.yaml
Updates the CI to use v3 alpha6
=> Depthai version update to v3 alpha6

.github/labeler.yaml, .github/workflows/add-metadata.yaml, .github/workflows/ci.yaml, .github/workflows/codecov.yaml
- Moved assigner and labeler to a separate workflow to be run on every PR
- Added workflow to update the base report for `codecov`
- Updated labeler configuration
=> Devops workflow updates

README.md, depthai_nodes/__init__.py
Version bumped to v0.1.1 and DAI version bump to alpha10
=> Release v0.1.1

depthai_nodes/ml/messages/img_detections.py
Workaround to until the `normalized` flag is available on Point2f and Size2f
=> Fix on range of values passed into Point2f and Size2f

.github/workflows/ci.yaml, .github/workflows/integration_tests.yaml, README.md, depthai_nodes/ml/messages/img_detections.py
Add `normalized` flag into Point2f and Size2f during the creation of `rotated_rect`.
Updated README to point to `depthai==3.0.0a11`
=> Update Point2f and Size2f to use normalized

depthai_nodes/parsing_neural_network.py
Refactoring of `ParsingNeuralNetwork` featuring:
- Build method signatures fix to match DAI allowed signatures
- Option to use strongly typed `getParser` method
- Add `numShaves` parameter to `setNNArchive` method to match DAI allowed signature
=> Ref: Parsing Neural Network

depthai_nodes/ml/parsers/utils/yolo.py
Added explicit YOLOV6R2 subtype to be inline with DAI
=> Added explicit Yolov6r2 type to be inline with DAI

depthai_nodes/node/parsing_neural_network.py, depthai_nodes/node/utils/detection_config_generator.py, tests/stability_tests/conftest.py, tests/unittests/test_nodes/test_threaded_host_nodes/conftest.py, tests/utils/nodes/mocks/__init__.py, tests/utils/nodes/mocks/sync_node.py
=> feat: ParsingNeuralNetwork add property to send out outputs of multiple heads in a single message

tests/end_to_end/main.py, tests/end_to_end/manual.py, tests/end_to_end/utils.py, tests/stability_tests/parallel.sh, tests/unittests/test_nodes/test_host_nodes/test_apply_colormap_node.py, tests/unittests/test_nodes/test_host_nodes/test_depth_merger_node.py, tests/unittests/test_nodes/test_host_nodes/test_img_detections_bridge_node.py, tests/unittests/test_nodes/test_host_nodes/test_img_detections_filter_node.py, tests/unittests/test_nodes/test_host_nodes/test_img_frame_overlay_node.py, tests/unittests/test_nodes/test_host_nodes/test_tiles_patcher_node.py, tests/unittests/test_nodes/test_host_nodes/test_tiling_node.py, tests/unittests/test_nodes/test_threaded_host_nodes/test_gather_data_node.py, tests/utils/__init__.py, tests/utils/constants.py, tests/utils/nodes/mocks/queue.py
We need better logging in E2E tests so we can see where the tests stopped. In the stability tests we need intermediate logs on all tests, leave out some unnecessary tests for stability (pnn, parser_generator), fix duration bug in some tests, add better description and improve memory limits on docker containers.
Tested with HIL team.
=> Tests: Stability tests update & better E2E logging. 

depthai_nodes/node/gather_data.py
=> Fixed docstrings

depthai_nodes/node/apply_colormap.py, tests/unittests/test_nodes/test_host_nodes/test_apply_colormap_node.py
You can define a custom, OpenCV compatible, colormap
=> Ability to define custom colormap

depthai_nodes/utils/detection_drawer.py
Fixed wrong docstring indentation
=> Fixed wrong docstring indentation

.github/workflows/e2e_tests.yaml, .github/workflows/stability_tests.yaml, tests/stability_tests/parallel.sh
HIL framework introcudes some breaking changes and this PR resolves them.
- `hil` command is renamed to `hil_runner`.
- We setup HIL framework with pip and add the path to the python package
- `GITLAB_TOKEN` is updated with new token that also has package permissions
We can wait for hil to be fully switched to new version, but the workflows already work
Ran a [E2E test ](https://github.com/luxonis/depthai-nodes/actions/runs/17757369766).
=> Update workflows with new HIL package.

depthai_nodes/node/detection_cropper.py
Create a `DetectionCropper` node that crops detections from frames.
https://app.clickup.com/t/86c5mz8c5
Manually tested on RVC2 and RVC4
Example usage for emotion recognition available here: [detection_cropper_example.py](https://github.com/user-attachments/files/22747465/detection_cropper_example.py)
=> create DetectionCropper node
