depthai_nodes/ml/messages/__init__.py
depthai_nodes/ml/messages/creators/__init__.py
depthai_nodes/ml/messages/creators/density.py
depthai_nodes/ml/messages/mapping.py
depthai_nodes/ml/parsers/__init__.py
depthai_nodes/ml/parsers/dmcount.py

Adding parser support for [DM-Count](https://github.com/cvlab-stonybrook/DM-Count/tree/master) crowd density estimation model. Moreover, I'm introducing a new message type for 2D numpy arrays of float values. It's used here to represent a density map but could also be re-used elsewhere in the library (e.g. for depth maps but this should go in a separate PR as we might actually also be able to merge the density and depth parsers - this is also why I'm not including any tests in this PR, as I want to have it passed to de-block experiments team and address this in the next PR).

feat: add DM-Count parser

---

depthai_nodes/ml/messages/__init__.py
depthai_nodes/ml/messages/clusters.py
depthai_nodes/ml/messages/creators/__init__.py
depthai_nodes/ml/messages/creators/clusters.py
depthai_nodes/ml/parsers/__init__.py
depthai_nodes/ml/parsers/lane_detection.py
depthai_nodes/ml/parsers/utils/ufld.py
examples/utils/parser.py
examples/visualization/detection.py
examples/visualization/mapping.py
examples/visualization/messages.py
media/coverage_badge.svg
tests/unittests/test_creators/test_clusters.py

This PR adds a Lane Detection parser for Super-fast-lane-detection models. There are two versions of the model so parser requires some parameters. The output of the parser are clusters of points. Each cluster represents one lane. So, for the easiest message representation, I suggest a new message type - Clusters.
PR also adds tests for cluster message and support in general example. MonocularDepthParser is removed from general example because of #57.

Lane detection parser.

---

depthai_nodes/ml/messages/classification.py
depthai_nodes/ml/messages/creators/__init__.py
depthai_nodes/ml/messages/creators/classification_sequence.py
depthai_nodes/ml/parsers/__init__.py
depthai_nodes/ml/parsers/ppocr.py
depthai_nodes/ml/parsers/segmentation.py
media/coverage_badge.svg
tests/unittests/test_creators/test_classification_sequence.py

Paddle OCR model outputs a sequence of classification probabilities for each possible character at each sequence step.
This PR adds a general postprocessing function, `classification_sequence_message`, that can be used for this model and similar ones. The `classification_sequence_message` finds the class (in the case of OCR: characters) with the maximum probability at each sequence step. It can optionally remove unwanted classes (such as padding, background, or blank characters) from the sequence, as well as concatenate them into words in the case of characters or into sentences in the case of complete words. The return type is a `depthai_nodes.Classification` message. Unit tests have also been added.
`ppocr.PaddleOCRParser` utilizes this message for the PaddleOCR model.

Paddle OCR Parser

---

depthai_nodes/ml/messages/__init__.py
depthai_nodes/ml/messages/creators/__init__.py
depthai_nodes/ml/messages/creators/detection.py
depthai_nodes/ml/messages/img_detections.py
depthai_nodes/ml/parsers/ppdet.py
media/coverage_badge.svg

This PR updated ppdet Parser to return a polygons instead of ImgDetections. The polygons are saved as `Keypoints` objects. This is done through the new `create_corner_detection_message` which is also available for other general detection models.
This hotfix does not include tests.

[HOT-FIX] Update ppdet to return polygons.

---

depthai_nodes/ml/parsers/__init__.py
depthai_nodes/ml/parsers/classification.py
depthai_nodes/ml/parsers/parser.py
depthai_nodes/ml/parsers/ppocr.py

This PR adds an updated Parser v2 example. New additions are: 
- A base `Parser` class that all other classes will inherit. 
- Updated sytax using `.build()` to be more in line with dai v3 syntax, the .build method accepts a list of dai.nn_archive.v1.Head objects or a Dictionary. If Head objects are parsed, they are converted to a dictionary.
Docstrings will be updated once the functionality is finalized. Variable names also can be adjusted.

Parser v2 example

---

depthai_nodes/ml/parsers/__init__.py
depthai_nodes/ml/parsers/base_parser.py
depthai_nodes/ml/parsers/classification.py
depthai_nodes/ml/parsers/parser.py
depthai_nodes/ml/parsers/parser_generator.py
depthai_nodes/ml/parsers/ppocr.py
depthai_nodes/ml/parsers/utils/__init__.py
depthai_nodes/ml/parsers/utils/decode_head.py

Adding a small refactor PR for the base parser. Expanding docstrings and fixing the type checking (the issue described [here](https://github.com/luxonis/depthai-nodes/pull/74#discussion_r1773055805)).
Moreover, I'm wondering if:
- the base parser should rather store `head` (depthai object) instead of `head_config` (dict). The functionality would stay the same but this would, in my opinion, make things more clear and readable. It would also simplify the code. I'm assuming the `head_config` is introduced to enable manual parser building (so that one could write a custom dict instead of providing a NN Archive). However, I think that the build method should be used only for building from a NN Archive and we use the parser-specific setter methods for manual building;
- based on the same logic …

Parsers-V2: Refactor Base Parser

---

depthai_nodes/ml/parsers/__init__.py
depthai_nodes/ml/parsers/utils/xfeat.py
depthai_nodes/ml/parsers/xfeat_mono.py
depthai_nodes/ml/parsers/xfeat_stereo.py

This PR changes the way XFeat output is parsed. Currently, we match two consecutive frames from the same input source - not really useful. Now, we introduce two parsers for XFeat - Mono and Stereo versions. Mono version works with one input source (e.g. one color camera) and lets you set the reference frame by triggering with `setTrigger()` method and then all future frames are matched to the reference frame. Stereo version works with two input sources (e.g. left and right camera) and always matches the "left" frame with the "right" frame. 
Additionally, postprocessing is improved - it is faster and uses only bilinear interpolation. Original implementation uses bilinear, bicubic and nearest. This does not affect the final results very much.
This PR is also not relevant to the Parsers V2.

XFeat parser for Mono and Stereo.

---

depthai_nodes/ml/messages/creators/detection.py
depthai_nodes/ml/messages/creators/regression.py
depthai_nodes/ml/messages/img_detections.py
depthai_nodes/ml/parsers/__init__.py
depthai_nodes/ml/parsers/regression.py
depthai_nodes/ml/parsers/utils/bbox.py
depthai_nodes/ml/parsers/utils/keypoints.py
depthai_nodes/ml/parsers/utils/nms.py
depthai_nodes/ml/parsers/utils/yunet.py
depthai_nodes/ml/parsers/yunet.py
tests/unittests/test_creators/test_detections.py

This PR adds a parsers-v2 refactor for `YuNetParser`, and adjusts `ImgDetectionExtended` message to accept the newly added `Keypoints` object and is also up-to-date with the newly planned changes that will get written in DAI. Detection message creator (`create_detection_message`) is also adjusted and now accepts only numpy arrays (this change also affects `MPPalmDetectionParser`, `SCRFDParser`, and `YOLOExtendedParser` which are not fixed in this PR).
NOTE: The PR also includes some pre-commit format fixing for the Regression parser and message.

Parsers-V2: Refactor YuNet Parser

---

depthai_nodes/ml/messages/creators/classification.py
depthai_nodes/ml/parsers/classification.py
depthai_nodes/ml/parsers/keypoints.py
depthai_nodes/ml/parsers/segmentation.py
examples/README.md
examples/main.py
examples/utils/parser.py
examples/utils/xfeat.py
examples/visualization/visualize.py
examples/visualization/visualizers/__init__.py
examples/visualization/visualizers/classification.py
examples/visualization/visualizers/detection.py
examples/visualization/visualizers/utils/message_parsers.py
examples/visualization/visualizers/xfeat.py
tests/unittests/test_creators/test_classification.py

In this PR we add support in examples for unsupported parsers including:
- MultiClassificationParser
- PaddleOCRParser
- PPTextDetectionParser
- XFeat Mono and Stereo parsers
XFeat example is a bit different so it is not implemented in the general example flow but its rather in its own function.
Next, I extended the MultiClassificationParser because it didnt have set methods. I also increased the tolerance in probability scores validation - if the scores sum to 1. The problem was with efficientnet-lite becuase it predicts 1000 classes so sometimes it didnt meet the criteria (maybe rounding errors or something?).
I adjusted Segmentation and Keypoint parsers so the warning (`Expected 1 output layer, got .... Taking the first one`) is not spammed in real time but rather only printed once.

Minor release preparation.

---

depthai_nodes/ml/parsers/__init__.py
depthai_nodes/parser_generator.py
depthai_nodes/parsing_neural_network.py

Adding a small change to the `ParsingNeuralNetwork` build method which now also accepts `dai.NNModelDescription` (next to `dai.NNArchive`). This is done to allow abstracted pipeline creation as shown in the DAI example [HERE](https://github.com/luxonis/depthai-core/blob/v3_develop/examples/python/NeuralNetwork/neural_network.py).
Moreover, ParserGenerator is moved one level higher to prevent errors with getting parser classes from the globals (`globals().get(parser_name)`).

Fix: ParsingNeuralNetwork and ParserGenerator

---

depthai_nodes/ml/messages/creators/detection.py
depthai_nodes/ml/messages/img_detections.py
depthai_nodes/ml/parsers/fastsam.py
depthai_nodes/ml/parsers/utils/fastsam.py
depthai_nodes/ml/parsers/utils/keypoints.py
depthai_nodes/ml/parsers/utils/masks_utils.py
depthai_nodes/ml/parsers/utils/yolo.py
depthai_nodes/ml/parsers/yolo.py
depthai_nodes/parser_generator.py

This PR refactors the last remaining parser FastSAM - because previously it was dependent on the YOLOExtended parser. Now its parent class is BaseParser. We dont need to pass input size anymore as it is calculated automatically from the output tensor shape by multiplying it with the stride.
I also moved two functions `_get_segmentation_outputs` and `reshape_seg_outputs` away from YOLO class into YOLO utils because the two functions are also used in FastSAM.
Validation logic in `ImgDetectionsExtended` for `masks` was not right for current masks in YOLOExtended. I just commented it because when we add new masks representetation we would probably need it.
`ImgDetectionsExtended` was not having option to add a confidence to the keypoint (YOLO Pose outputs also `visibility` for each keypoint - …

Parsers-V2: Refactor FastSAM & YOLO fixes.

---

depthai_nodes/ml/parsers/lane_detection.py
depthai_nodes/ml/parsers/utils/ufld.py
examples/visualization/visualizers/detection.py

Output of `LaneDetectionParser` parser has now `x` and `y` coordinates normalized to input image.

Normalized lane coordinates

---

.github/workflows/ci.yaml
README.md
depthai_nodes/__init__.py

Updated CI badge, DAI version and depthai-nodes version

Release v0.1.0

---

depthai_nodes/parser_generator.py

This PR adds support for YOLO and SSD models in `ParserGenerator`. It uses dai's `DetectionParser` to parse the outputs. We can now instatiate `ParsingNeuralNetwork` node with yolo's or ssd's archives.

Add support for YOLO and SSD in ParserGenerator.

---

depthai_nodes/ml/parsers/base_parser.py
depthai_nodes/ml/parsers/lane_detection.py
depthai_nodes/ml/parsers/utils/yunet.py
depthai_nodes/ml/parsers/yunet.py
depthai_nodes/parser_generator.py

Adding a fix to the parsers that require model input size and cannot deduce it from the model outputs (`YuNetParser` and `LaneDetectionParser`) by extending the `build()` method to look for the the `input_shape` within the `head_config`. Additionally, `ParserGenerator` is updated to set the `input_shape` argument aromatically based on the relevant `NN Archive`.
Some additional changes:
- the default `input_size` was removed for the `LaneDetectionParser`,
- all `input_shape` variable/parameter names were changed to `input_size` because it better fits their meaning (shape resembles NCHW/NHWC whereas we only describe HW) → this is more or less a refactoring change only, but it also effects the `input_size` setters for the two parsers (`setInputShape` → `setInputSize`)
The implemented changes …

fix: input size setting

---

depthai_nodes/ml/messages/classification.py
depthai_nodes/ml/messages/img_detections.py
depthai_nodes/ml/messages/prediction.py

This PR improves 3 messages:
1. `Predictions` msg - we add a property `prediction` for retrieving first prediction value. This is useful because Regression parser many times returns one value and to get the value we must type `message.predictions[0].prediction`. Now, we will just write `message.prediction`.
2. `Classification` msg - same idea as with Predictions msg. to get the most probable class and score we add two properties: `top_class` and `top_score`. 
3. `ImgDetectionExtended` msg - two methods are added for easy conversion to [x1,y1,x2,y2] bbox and for [[x1,y1], [x2,y2],[x3,y3],[x4,y4]] rotated bbox (going from the top-left and clockwise)

Message improvements (properties and methods).

---

depthai_nodes/ml/messages/classification.py

This PR just updates the docstring becuase #124 was close early. The discussion about it can be found in #124.

Docstring update in Classification msg.

---

.github/workflows/e2e_tests.yaml
tests/end_to_end/main.py

This PR improves logging in GH actions. Now, The besides the test status (FAILED, SKIPPED) also reason is given e.g. `Can't connect to the device...` or `Pipeline crashed` etc.

Better logging in E2E tests.

---

depthai_nodes/ml/messages/creators/detection.py
depthai_nodes/ml/messages/img_detections.py
depthai_nodes/ml/parsers/fastsam.py
depthai_nodes/ml/parsers/mlsd.py
depthai_nodes/ml/parsers/superanimal_landmarker.py
depthai_nodes/ml/parsers/utils/masks_utils.py
depthai_nodes/ml/parsers/yolo.py

This PR forces NCHW tensor output when calling `getTensor(...)` method instead of manually checking the shapes and transposing them inside parsers.
Affected Parsers:
- MLSD parser
- FastSAM parser
- YOLOExtended parser
- SuperAnimal parser: removed unnecessary check for shapes.
One yolo util function (`reshape_seg_outputs`) is removed - not needed anymore.
Additionally, `ImgDetectionExtended`'s `masks` parameter now expects int16 and not int8 (introduced in some previous PR) + detection creator function converts `masks` to int16 instead of int8.

Force NCHW tensor order.

---

depthai_nodes/ml/parsers/classification.py
depthai_nodes/ml/parsers/classification_sequence.py
depthai_nodes/ml/parsers/utils/softmax.py
depthai_nodes/ml/parsers/utils/ufld.py

This PR implements softmax util function and refactors some parsers so they use softmax from utils now.

Single softmax function.

---

depthai_nodes/ml/parsers/classification.py
depthai_nodes/ml/parsers/embeddings.py
depthai_nodes/ml/parsers/fastsam.py
depthai_nodes/ml/parsers/keypoints.py
depthai_nodes/ml/parsers/mediapipe_palm_detection.py
depthai_nodes/ml/parsers/yolo.py

This PR adds some validation logic to parser's setter methods like `setAnchors()`. It also fixes some docstrings/types and moves some code in Embeddings parser to follow the structure: 1. Constructor, 2. setters, 3. build, 4. run.

Validation in setters and parser structure.

---

tests/end_to_end/manual.py
tests/end_to_end/test_e2e.py
tests/end_to_end/utils.py

Checks added in E2E tests:
-  Catches the error when downloading the model from ZOO
-  Catches the error when loading the NN archive
-  Checks if the model has more than one output
Every catch has a `print(e)` so we know whats wrong when running it with `manual.py`
This PR also adds `ImageManipV2` node to the pipeline if the model input size is not divisible by 2 (e.g. 513x513 in deeplab) or the input size is too small. We request 2 or 4 times bigger input size from the camera and then resize it down to model's input size with `ImageManipV2` node.
This feature now runs more models in E2E testing.

E2E Tests: ImageManip node and better checks.

---

depthai_nodes/ml/messages/classification.py
depthai_nodes/ml/messages/clusters.py
depthai_nodes/ml/messages/img_detections.py
depthai_nodes/ml/messages/keypoints.py
depthai_nodes/ml/messages/lines.py
depthai_nodes/ml/messages/map.py
depthai_nodes/ml/messages/prediction.py
depthai_nodes/ml/messages/segmentation.py
depthai_nodes/ml/parsers/classification.py
depthai_nodes/ml/parsers/classification_sequence.py
depthai_nodes/ml/parsers/fastsam.py
depthai_nodes/ml/parsers/hrnet.py
depthai_nodes/ml/parsers/image_output.py
depthai_nodes/ml/parsers/keypoints.py
depthai_nodes/ml/parsers/lane_detection.py
depthai_nodes/ml/parsers/map_output.py
depthai_nodes/ml/parsers/mediapipe_palm_detection.py
depthai_nodes/ml/parsers/mlsd.py
depthai_nodes/ml/parsers/ppdet.py
depthai_nodes/ml/parsers/regression.py
depthai_nodes/ml/parsers/scrfd.py
depthai_nodes/ml/parsers/segmentation.py
depthai_nodes/ml/parsers/superanimal_landmarker.py
depthai_nodes/ml/parsers/utils/ppdet.py
depthai_nodes/ml/parsers/yolo.py
depthai_nodes/ml/parsers/yunet.py

This PR adds the following:
1) `dai.ImgTransformations` attribute to all depthai-nodes messages. This is necessary as the information inside dai.ImgTransofrmations is needed in later nodes for dai.ImgManip, and for visualization purposes as width, height and other values are stored in this attribute.
2) adds some improvements to Text Detection parser and Palm detection parser where the angle is rounded to a full degree.
3) Make Text detection parser more robust and simplify some postprocessing functions, making the detections much more reliable

Add dai.ImgTransformations to messages and improvements to Text detection parser

---

.github/workflows/e2e_tests.yaml
.github/workflows/integration_tests.yaml
.gitignore
requirements-dev.txt
tests/conftest.py
tests/integration_tests/README.md
tests/integration_tests/check_messages.py
tests/integration_tests/config.py
tests/integration_tests/extract_nn_data.py
tests/integration_tests/main.py
tests/integration_tests/manual.py
tests/integration_tests/parser_test.py
tests/integration_tests/utils.py

This PR adds integration tests for parsers. Tests work in a similar way as end-2-end tests. We have `main.py` where we can locally run a test and we can trigger the tests in the GH actions.
These tests are designed to simulate a neural network output and send it to the parser node. The parser node will parse the output and return the message. The tests check if the parser outputs the expected message. Since we know what `NNData` we are sending to the parser, we can check if the outputted message is correct.
The testing pipeline is as follows:
1. Load the neural network archive.
2. Load the parser node with `ParserGenerator` based on the NN archive.
3. Read and load the `NNData` from pickle file. It contains the output of the neural network.
4. Send the `NNData` to the parser node.
5. Read …

Integration tests for parsers.

---

depthai_nodes/parsing_neural_network.py

- Added getParser() method to ParsingNeuralNetwork Class with a default value for `parserID = 0`

Expose parsers when building a pipeline through ParsingNeuralNetwork

---

.github/workflows/e2e_tests.yaml
.github/workflows/integration_tests.yaml
depthai_nodes/ml/parsers/image_output.py
tests/integration_tests/manual.py
tests/integration_tests/parser_test.py

This PR adds the ability to run integration tests on all connected platforms (RVC2, RVC4). If there are multiple RVC2 devices connected it will only select one. 
Additionally, there was a bug in `ImageOutputParser` because we were setting the attribute `transformation` of the `dai.ImgFrame` which doesn't have this attribute - fixing it with the method `setTransformations()`. Hopefully, this bugs will be catched now:)
Lastly, we updated the CI workflows for E2E and integration tests with the option to specify which depthai version we want - the specified version will then be installed in the testbed server before the tests run. CI jobs will also wait until testbed is free and wont fail the job if testbed is reserved.
Integration tests are included in the CI for every PR. They are triggered …

Integration tests: Small updates & triggering in every PR.

---

depthai_nodes/ml/messages/creators/clusters.py

This PR simply fixes one bug in clusters creator.

Fix validation in cluster creation.

---

.pre-commit-config.yaml
depthai_nodes/ml/parsers/xfeat.py

This PR fixes small bug in XFeat parser where we didn't request NCHW storage order, so RVC4 version didn't work.

Storage order fix in XFeat parser.

---

.github/workflows/e2e_tests.yaml
.github/workflows/integration_tests.yaml
tests/conftest.py
tests/end_to_end/README.md
tests/end_to_end/main.py
tests/end_to_end/manual.py
tests/end_to_end/test_e2e.py
tests/end_to_end/utils.py
tests/integration_tests/README.md
tests/integration_tests/extract_nn_data.py
tests/integration_tests/main.py
tests/integration_tests/manual.py

This PR expands Readmes in E2E and Integration tests so the required parameters are described.

Tests: Expand docs.

---

.github/workflows/e2e_tests.yaml
.github/workflows/integration_tests.yaml
tests/end_to_end/manual.py

This PR improves reservation name for reserving testbeds. The name reflects the current GH job.
We also introduce End-to-end tests on every PR. Actually, the E2E tests run on every push to main - that means every time when the PR is merged. This way we dont run the test on every commit push to the PR but rather when the PR is merged. If any tests fail we should address this in the new PR. Thoughts @klemen1999 @jkbmrz @aljazkonec1 ?

Tests: Update triggers & better reservation name.

---

depthai_nodes/ml/messages/creators/classification.py
depthai_nodes/ml/parsers/classification.py
depthai_nodes/ml/parsers/classification_sequence.py
depthai_nodes/ml/parsers/embeddings.py
depthai_nodes/ml/parsers/fastsam.py
depthai_nodes/ml/parsers/hrnet.py
depthai_nodes/ml/parsers/image_output.py
depthai_nodes/ml/parsers/keypoints.py
depthai_nodes/ml/parsers/lane_detection.py
depthai_nodes/ml/parsers/map_output.py
depthai_nodes/ml/parsers/mediapipe_palm_detection.py
depthai_nodes/ml/parsers/mlsd.py
depthai_nodes/ml/parsers/ppdet.py
depthai_nodes/ml/parsers/regression.py
depthai_nodes/ml/parsers/scrfd.py
depthai_nodes/ml/parsers/segmentation.py
depthai_nodes/ml/parsers/superanimal_landmarker.py
depthai_nodes/ml/parsers/utils/ppdet.py
depthai_nodes/ml/parsers/xfeat.py
depthai_nodes/ml/parsers/yolo.py
depthai_nodes/ml/parsers/yunet.py

This PR adds inheritance of frame sequence numbers to all parser output messages. When a frame is created in camera node it has a sequence number, this number is then forwarded (similarly like timestamp) in nodes that manipulate the frame such as NeuralNetwork, ImageManipV2, .... 
To keep forwarding consistent with these nodes, I added it to all message outputs of parsers.
In addition I also added a small change to Text Detection post processing.

Add sequence number inheritence to all parsers

---

depthai_nodes/ml/parsers/utils/denormalize.py

Adding a quick fix to prevent divison-by-zero when we un-normalize images.

fix: normalization to prevent divison-by-zero

---

depthai_nodes/nodes/utils/__init__.py
depthai_nodes/nodes/utils/detection_config_generator.py
tests/unittests/test_nodes/test_detection_config_generator.py

Moving detection manip config script (`generate_script_content`) from DepthAI experiments. Also includes test for the script.

feat: Detection Manip Config Script

---

depthai_nodes/nodes/depth_merger.py

This PR fixes a bug in DepthMerger when shrinking factor is used. Previously, we passed shrunk xmin,ymin,xmax,ymax also to the SpatialDetection object and that resulted in shrunk bbox during visualization. We only want to shrink the ROI for calculating depth.

Bug fix: DepthMerger

---

depthai_nodes/ml/messages/img_detections.py
depthai_nodes/ml/messages/keypoints.py
depthai_nodes/ml/parsers/utils/yolo.py
depthai_nodes/utils/__init__.py
depthai_nodes/utils/logging.py

Previous setup of the logging module led to duplicit logs when using the Python `logging` module along the `depthai-nodes` package as a dependency. 
To get the package logger use the `get_logger` method from `depthai_nodes.utils`.
All the files and classes that were using the logger were changed to use the package logger.
Was tested on simple script, where a custom logger was configured and log message from `depthai-nodes` was triggered. The logs were not duplicated by `depthai-nodes` logger. The logs from `depthai-nodes` were successfully logged.

Fix: Global Logging

---

tests/end_to_end/Dockerfile
tests/end_to_end/manual.py
tests/integration_tests/Dockerfile

This PR fixes two problems: 1. Unsupported 30 FPS in RVC2 Lite cameras and 2. some edge case in Docker image that caused problems.
We are changing testing script in E2E testing to always request 20 FPS from the camera - this is supported on all devices and it doesnt matter because we only get the first frame and finish the test.
Second change regarding the docker images is in the dockerfiles. We remove second `git pull` after checking out the desired branch. 
No affected services or breaking changes.
We can monitor if the tests work in the actions tab.
It was tested manually and it worked.

Tests: Fix edge case in HIL testing.

---

depthai_nodes/ml/messages/creators/detection.py
depthai_nodes/ml/parsers/detection.py
depthai_nodes/ml/parsers/mediapipe_palm_detection.py
depthai_nodes/ml/parsers/scrfd.py
depthai_nodes/ml/parsers/yolo.py
depthai_nodes/ml/parsers/yunet.py
tests/integration_tests/main.py
tests/unittests/test_creators/test_detections.py

We have `label_name` in the `ImgDetectionExtended` message but we do not set this field in the parsers. Setting this will allow the user to extract the class with `detection.label_name`.
I adjusted `YOLOExtendedParser` and `DetectionParser` to get the class names from nn archive inside the `build` method. Relevant detection parsers are also adjusted.
No breaking changes.
No plan.
It was tested on all affected parsers. For yolo versions I tested pose estimation model and YOLOP.

Set label names in detection parsers.

---

depthai_nodes/ml/parsers/mediapipe_palm_detection.py

We are also passing 4 keypoints (4 corner points of the bbox) to the ImgDetectionExtended msg which is not relevant anymore due to OBB support. So we remove this.
Removing the keypoints argument in creator function for detection message.

Remove keypoints from PalmDetection.

---

depthai_nodes/message/img_detections.py

This PR removes a small, RVC2 specific, type check that was added due to a depthai bug. As of depthai 3.13 this bug has been patched and the type check is no longer needed.

Remove RVC2 specific check

---

.github/workflows/e2e_tests.yaml
.github/workflows/integration_tests.yaml
README.md
depthai_nodes/__init__.py
tests/end_to_end/README.md
tests/integration_tests/README.md

Release v0.2.0

---

depthai_nodes/node/parsers/detection.py

By adding Mobile object localizer model to our ZOO we need a parser for it. I think we can use `DetectionParser` and just define the `run` method for `general simple` object detector - get bboxes and scores and compute NMS and return the message.
We add the `run` method to the `DetectionParser` class so it can be used as standalone parser.
Does not affect other detection parsers as they all override `run` method.
Tested with general example in dai-experiments on Mobile obj. localizer, YuNet, SCRFD, PalmDetection models.

Updated DetectionParser.

---

depthai_nodes/message/classification.py
depthai_nodes/message/clusters.py
depthai_nodes/message/img_detections.py
depthai_nodes/message/keypoints.py
depthai_nodes/message/lines.py
depthai_nodes/message/map.py
depthai_nodes/message/prediction.py
depthai_nodes/message/segmentation.py
depthai_nodes/node/parsers/classification.py
depthai_nodes/node/parsers/classification_sequence.py
depthai_nodes/node/parsers/detection.py
depthai_nodes/node/parsers/fastsam.py
depthai_nodes/node/parsers/hrnet.py
depthai_nodes/node/parsers/keypoints.py
depthai_nodes/node/parsers/lane_detection.py
depthai_nodes/node/parsers/map_output.py
depthai_nodes/node/parsers/mediapipe_palm_detection.py
depthai_nodes/node/parsers/mlsd.py
depthai_nodes/node/parsers/ppdet.py
depthai_nodes/node/parsers/regression.py
depthai_nodes/node/parsers/scrfd.py
depthai_nodes/node/parsers/segmentation.py
depthai_nodes/node/parsers/superanimal_landmarker.py
depthai_nodes/node/parsers/yolo.py
depthai_nodes/node/parsers/yunet.py

This PR adds the following methods:
1) `setTransformation()` wrapper method to all message types. This is done in an effort to unify the syntax with depthai-core. The usage can be seen in the parsers as now the `setTransformation()` is used instead of `msg.transformation = transformation`
2) `getPoints2f()` and `getPoints3f()` are helper methods for the Keypoints message type. The purpose is to simplify the conversion process from depthai-nodes types to depthai-core types.
No breaking changes are expected as 1) are wrapper functions and 2) are helper functions.

Add setTransformation and getPoints methods

---

depthai_nodes/node/apply_colormap.py

Fixing bugs in `ApplyColormap` node:
- The `timestamp` and `sequence number` info of the outgoing message are not set correctly which is causing syncing issues in examples where the outgoing message is overlaid on top of other messages (e.g. in the `depthai-experiments/.../generic-example` with the `--overlay` attribute);
- the `process()` method is not accepting the `SegmentationMask` messages produced by some models.
- The `timestamp` and `sequence number` values of the outgoing message are matched with those of the incoming message;
- the `process()` method is modified to also accept the `SegmentationMask` message type.
The changes were tested by running the updated `generic-example` (taken from …

fix: ApplyColormap output message

---

depthai_nodes/message/map.py
depthai_nodes/node/apply_colormap.py
depthai_nodes/node/utils/copy_message.py
tests/unittests/test_nodes/test_host_nodes/test_copy_message.py

Fixing a bug in `ApplyColor` node that was causing "flickering" visualizations.
`ApplyColor` node was mistakenly modifying the incoming messages. Adding a message copy mechanism to prevent this from happening.
None
None
Was tested using the following models:
- mediapipe-selfie-segmentation:256x144 (`SegmentationMask` output)
- midas-v2-1:small-256x192 (`Map2D` output)

Fix: Background flickering

---

depthai_nodes/node/__init__.py
depthai_nodes/node/host_parsing_neural_network.py
depthai_nodes/node/parser_generator.py
depthai_nodes/node/parsing_neural_network.py
tests/unittests/test_nodes/test_threaded_host_nodes/test_host_parsing_neural_network_node.py
tests/unittests/test_nodes/test_threaded_host_nodes/test_parser_generator_node.py

Have alternative to `ParsingNeuralNetwork` that uses no device nodes parsers (e.g. `dai.node.DetectionParser`) and restricts only to host node parsers (e.g. `YOLOExtendedParser`). Main advantages of host node parsers is possibility to configure them at runtime, which is not possible for parsers running on device.
`ParserGenerator` is changed such that `build` method accepts `host_only` flag. `ParsingNeuralNetwork` is changed to have the parser generation easily changed by inheritance. The `HostParsingNeuralNetwork` class is added.
No breaking changes.
Tests for the node added and passing. More tests added and passing for `ParsingGenerator`, covering the new `host_only` flag functionality.

Feat: Host Parsing Neural Network

---

depthai_nodes/message/creators/detection.py
depthai_nodes/message/creators/keypoints.py
depthai_nodes/message/img_detections.py
depthai_nodes/message/keypoints.py
depthai_nodes/node/parsers/hrnet.py
depthai_nodes/node/parsers/keypoints.py
depthai_nodes/node/parsers/superanimal_landmarker.py
depthai_nodes/node/parsers/yolo.py
tests/unittests/test_messages/test_img_detections_msg.py

`Keypoints` message does not contain information about skeleton edges (connection pairs between kpts to draw a skeleton). Its useful when visualizing default message.
We modify `Keypoints` and `ImgDetectionExtedend` messages. `Keypoints` now also have `labels` (optional name of keypoints) and `edges` (connection pairs). `ImgDetectionExtended` now has `_keypoints` attribute as `Keypoints` object (and not `List[Keypoint]` anymore), so setter accepts `Keypoints` object and getter returns `List[Keypoint]`. `Keypoint` object is needed because we need to access the skeleton information inside visualization method.
I changed the NN archives, so they all have field `skeleton_edges` (only relevant models - Objectron, HRNet, etc.).
Tested with generic example and models: …

Message: Add skeleton to Keypoints.

---

depthai_nodes/node/__init__.py
depthai_nodes/node/apply_colormap.py
depthai_nodes/node/base_host_node.py
depthai_nodes/node/depth_merger.py
depthai_nodes/node/img_detections_bridge.py
depthai_nodes/node/img_detections_filter.py
depthai_nodes/node/img_frame_overlay.py
depthai_nodes/node/img_frame_sender.py
depthai_nodes/node/tiles_patcher.py
tests/unittests/test_nodes/test_host_nodes/conftest.py

Based on the [comment](https://github.com/luxonis/depthai-nodes/pull/192#discussion_r2021554304) in #192, we are missing an abstract class with platform extraction functionality. Adding it limits code repetition in host nodes and centralizes the control over the `ImgFrame.Type` settings for individual platforms.
Adding the `BaseHostNode`, an abstract class with platform extraction functionality, and using it as a parent in all of our host nodes.
None
None
Tested by running the `depthai-experiments/neural-networks/generic-example` using the `midas-v2-1:small-256x192` model both on RVC2 and RVC4.

Feat: Add BaseHostNode

---

depthai_nodes/constants.py
depthai_nodes/message/classification.py
depthai_nodes/message/img_detections.py
depthai_nodes/message/keypoints.py
depthai_nodes/message/lines.py
depthai_nodes/message/prediction.py
depthai_nodes/utils/annotation_helper.py

`AnnotaitonHelper` node can have default colors which are aligned with official Luxonis colors. Same goes for default visualizations of messages.
Added primary, secondary, and primary transparent (used as fill color in bboxes - similar to Visualizer).
It has some naming changes which may lead to broken experiments.
Tested on affected messages.

Default AnnotationHelper colors.

---

depthai_nodes/node/img_detections_bridge.py

Adding an option to provide label encodings to the `ImgDetectionsBridge` used to generate label names during conversion.
Adding a `label_encoding` parameter to the `ImgDetectionsBridge.build()`. This is then used to generate `label_name`s during `dai.ImgDetections` to `ImgDetectionsExtended` conversion (the first doesn't store label names while the second can).
None
None
Default tests.

fead: add label endocoding to ImgDetectionsBridge

---

depthai_nodes/message/keypoints.py

`Keypoint` message `confidencesetter` doesn't accept `-1.0` (the default confidence value).
Add an exception to the `confidence.setter` to also accept `-1.0`.
None
None
Unittests.

fix: Keypoint confidence setter

---

depthai_nodes/message/img_detections.py
depthai_nodes/message/keypoints.py
depthai_nodes/message/lines.py
tests/unittests/test_messages/test_img_detections_msg.py
tests/unittests/test_messages/test_keypoints_msg.py
tests/unittests/test_messages/test_lines_msg.py

A special case happens in confidence setter when confidence is above 1 and below 1.1. It clips the confidence to min(0, max(1, conf)) which can later throw an error as 0 and 1 are not floats.

[FIX] Float confidence

---

depthai_nodes/node/parsers/mediapipe_palm_detection.py
depthai_nodes/node/parsers/scrfd.py
depthai_nodes/node/parsers/utils/fastsam.py
depthai_nodes/node/parsers/utils/medipipe.py
depthai_nodes/node/parsers/utils/mlsd.py
depthai_nodes/node/parsers/utils/ppdet.py
depthai_nodes/node/parsers/utils/scrfd.py
depthai_nodes/node/parsers/utils/xfeat.py
depthai_nodes/node/parsers/utils/yolo.py
depthai_nodes/node/parsers/utils/yunet.py
depthai_nodes/node/parsers/yunet.py

Some of the parsers are not the optimal.
- `YuNetParser` - cached anchors,  unnecessary np.where (replaced with np.clip), general vectorization
- `YOLOExtendedParser` - decoding speed up and pre-filtering before the NMS
- `PPDetParser` - 1. Dilation kernel reduced: Faster, less small blobs, 2. Small areas filtered before sorting: Reduces number of contours to sort/loop. 3. Top-N selection uses np.argpartition: O(N) not O(N log N) as with full sort. 4. Direct construction of output arrays: Minimizes list->array conversion overhead. 5. Less shape shuffling, no unnecessary np.reshape.
- `MLSDParser` - Explicit python loop removed and replaced with numpy; usage of batched gather
- `SCRFDParser` - Caching anchors
- `MPPalmDetectionParser` - Caching anchor
- `FastSAMParser` - yolo part decoding …

Parser optimizations.

---

.github/workflows/e2e_tests.yaml

We have static matrix with [rvc2, rvc4], so if we want to run only one platform two jobs are picked up and both performing the same job.
Adding parameter to select both, rvc2, rvc4 option and then dynamically creating matrix for it. It fixes BOM tests.

E2E tests: Add option to select only one platform.

---

depthai_nodes/node/parsers/utils/yolo.py

In some YOLO variants the “objectness” score is not meaningful (e.g. all ones). Filtering by objectness before non-maximum suppression can therefore discard valid, high-confidence detections. This change ensures we only apply objectness-based filtering when the model actually produces different objectness scores.
- Only if not all objectness values are identical and the total number of detections exceeds `max_nms` do we sort and trim by objectness.
- Otherwise we fall back to the previous behavior of applying NMS on all detections regardless of objectness.

Apply objectness-based filtering only when real objectness scores are present

---

depthai_nodes/message/map.py
depthai_nodes/message/segmentation.py
depthai_nodes/node/apply_colormap.py

ApplyColormap node did not propagate image transformations from its input to the output. This could cause crashes and wrong behaviour in other (depthai) nodes that rely on transformation.

Fix: Add transformations to ApplyColormap node
